eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: Customer
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: Customer
      port: 27017
server:
  port: 8082
management:
 endpoints:
  web:
    exposure:
      include: '*'
